name: Deploy-Book
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: 
    - cron: "0 */12 * * *" 

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'

    # Install dependencies

    - name: Install dependencies
      run: |
        sudo apt-get install jupyter -y --fix-missing
        python -m pip install nbconvert
         
    - name: Run Notebooks
      env:
        GH_TOKEN:  ${{ secrets.GH_TOKEN }}
      run: |
         jupyter nbconvert  CreepDetector.ipynb
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
          default_author: github_actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

    - name: Build the book
      run: |
        jupyter-book build .
